# Generated by Django 4.1.2 on 2022-10-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dribk',
            new_name='Drink',
        ),
    ]
